function all_sequences = load_all_sequences(env_parameters)
%Loads all the sequences

base_sequence_path = [env_parameters.sequence_dir, '/'];

Basketball = struct('name','Basketball', 'path',[base_sequence_path 'Basketball/img/'],'startFrame',1, 'endFrame',725, 'nz','4', 'ext','jpg', 'init_rect',[214,198,81,34]);
Biker = struct('name','Biker', 'path',[base_sequence_path 'Biker/img/'],'startFrame',1, 'endFrame',142, 'nz','4', 'ext','jpg', 'init_rect',[94, 262,26, 16]);
BlurCar3 = struct('name','BlurCar3', 'path',[base_sequence_path 'BlurCar3/img/'],'startFrame',3, 'endFrame',359, 'nz','4', 'ext','jpg', 'init_rect',[236, 228, 64, 80]);
BlurBody = struct('name','BlurBody', 'path',[base_sequence_path 'BlurBody/img/'],'startFrame',1, 'endFrame',334, 'nz','4', 'ext','jpg', 'init_rect',[48,400,319,87]);
Bolt = struct('name','Bolt', 'path',[base_sequence_path 'Bolt/img/'],'startFrame',1, 'endFrame',350, 'nz','4', 'ext','jpg', 'init_rect',[165,336,61,26]);
Box = struct('name','Box', 'path',[base_sequence_path 'Box/img/'],'startFrame',1, 'endFrame',670, 'nz','4', 'ext','jpg', 'init_rect',[143,478,111,80]);
CarScale = struct('name','CarScale', 'path',[base_sequence_path 'CarScale/img/'],'startFrame',1, 'endFrame',252, 'nz','4', 'ext','jpg', 'init_rect',[166,6,26,42]);
Coke = struct('name','Coke', 'path',[base_sequence_path 'Coke/img/'],'startFrame',1, 'endFrame',291, 'nz','4', 'ext','jpg', 'init_rect',[160,298,80,48]);
Coupon = struct('name','Coupon', 'path',[base_sequence_path 'Coupon/img/'],'startFrame',1, 'endFrame',327, 'nz','4', 'ext','jpg', 'init_rect',[63,144,89,57]);
Crossing = struct('name','Crossing', 'path',[base_sequence_path 'Crossing/img/'],'startFrame',1, 'endFrame',120, 'nz','4', 'ext','jpg', 'init_rect',[151,205,50,17]);
Crowds = struct('name','Crowds', 'path',[base_sequence_path 'Crowds/img/'],'startFrame',1, 'endFrame',347, 'nz','4', 'ext','jpg', 'init_rect',[311,561,51,22]);
DragonBaby = struct('name','DragonBaby', 'path',[base_sequence_path 'DragonBaby/img/'],'startFrame',1, 'endFrame',113, 'nz','4', 'ext','jpg', 'init_rect',[83,160,65,56]);
FaceOcc1 = struct('name','FaceOcc1', 'path',[base_sequence_path 'FaceOcc1/img/'],'startFrame',1, 'endFrame',250, 'nz','4', 'ext','jpg', 'init_rect',[69,118,162,114]);
Human7 = struct('name','Human7', 'path',[base_sequence_path 'Human7/img/'],'startFrame',1, 'endFrame',250, 'nz','4', 'ext','jpg', 'init_rect',[111,110,116,37]);
Human9 = struct('name','Human9', 'path',[base_sequence_path 'Human9/img/'],'startFrame',1, 'endFrame',305, 'nz','4', 'ext','jpg', 'init_rect',[113,93,109,34]);
Ironman = struct('name','Ironman', 'path',[base_sequence_path 'Ironman/img/'],'startFrame',1, 'endFrame',166, 'nz','4', 'ext','jpg', 'init_rect',[85,206,57,49]);
Jogging_1 = struct('name','Jogging_1', 'path',[base_sequence_path 'Jogging/img/'],'startFrame',1, 'endFrame',307, 'nz','4', 'ext','jpg', 'init_rect',[98,111,101,25]);
KiteSurf = struct('name','KiteSurf', 'path',[base_sequence_path 'KiteSurf/img/'],'startFrame',1, 'endFrame',84, 'nz','4', 'ext','png', 'init_rect',[41,204,30,23]);
Liquor = struct('name','Liquor', 'path',[base_sequence_path 'Liquor/img/'],'startFrame',1, 'endFrame',1200, 'nz','4', 'ext','jpg', 'init_rect',[152,256,210,73]);
Man = struct('name','Man', 'path',[base_sequence_path 'Man/img/'],'startFrame',1, 'endFrame',134, 'nz','4', 'ext','jpg', 'init_rect',[48,69,39,26]);
MotorRolling = struct('name','MotorRolling', 'path',[base_sequence_path 'MotorRolling/img/'],'startFrame',1, 'endFrame',164, 'nz','4', 'ext','jpg', 'init_rect',[68,298,125,122]);
Shaking = struct('name','Shaking', 'path',[base_sequence_path 'Shaking/img/'],'startFrame',1, 'endFrame',365, 'nz','4', 'ext','jpg', 'init_rect',[135,225,71,61]);
Singer2 = struct('name','Singer2', 'path',[base_sequence_path 'Singer2/img/'],'startFrame',1, 'endFrame',366, 'nz','4', 'ext','jpg', 'init_rect',[149,298,122,67]);
Soccer = struct('name','Soccer', 'path',[base_sequence_path 'Soccer/img/'],'startFrame',1, 'endFrame',392, 'nz','4', 'ext','jpg', 'init_rect',[135,302,81,67]);
Subway = struct('name','Subway', 'path',[base_sequence_path 'Subway/img/'],'startFrame',1, 'endFrame',175, 'nz','4', 'ext','jpg', 'init_rect',[88,16,51,19]);
Surfer = struct('name','Surfer', 'path',[base_sequence_path 'Surfer/img/'],'startFrame',1, 'endFrame',376, 'nz','4', 'ext','jpg', 'init_rect',[137,275,26,23]);
Tiger1 = struct('name','Tiger1', 'path',[base_sequence_path 'Tiger1/img/'],'startFrame',1, 'endFrame',354, 'nz','4', 'ext','jpg', 'init_rect',[88,232,84,76]);
Trans = struct('name','Trans', 'path',[base_sequence_path 'Trans/img/'],'startFrame',1, 'endFrame',124, 'nz','4', 'ext','jpg', 'init_rect',[51,196,194,139]);
Walking = struct('name','Walking', 'path',[base_sequence_path 'Walking/img/'],'startFrame',1, 'endFrame',412, 'nz','4', 'ext','jpg', 'init_rect',[439,692,79,24]);
Walking2 = struct('name','Walking2', 'path',[base_sequence_path 'Walking2/img/'],'startFrame',1, 'endFrame',500, 'nz','4', 'ext','jpg', 'init_rect',[132,130,115,31]);

all_sequences = {...
    Basketball, ...
    Biker, ...
    BlurCar3, ...
    BlurBody, ...
    Bolt, ...
    Box, ...
    CarScale, ...
    Coke, ...
    Coupon, ...
    Crossing, ...
    Crowds, ...
    DragonBaby, ...
    FaceOcc1, ...
    Human7, ...
    Human9, ...
    Ironman, ...
    Jogging_1, ...
    KiteSurf, ...
    Liquor, ...
    Man, ...
    MotorRolling, ...
    Singer2, ...
    Shaking, ...
    Soccer, ...
    Subway, ...
    Surfer, ...
    Tiger1, ...
    Trans, ...
    Walking, ...
    Walking2 ...
    };

for seq_idx = 1:length(all_sequences)
    all_sequences{seq_idx}.len = all_sequences{seq_idx}.endFrame - all_sequences{seq_idx}.startFrame;
    all_sequences{seq_idx}.frames = cell(all_sequences{seq_idx}.len, 1);
    for n = 1:all_sequences{seq_idx}.len
        image_no = all_sequences{seq_idx}.startFrame + (n - 1);
        nz = all_sequences{seq_idx}.nz;
        filename = [all_sequences{seq_idx}.path sprintf(['%0' nz 'd'],image_no) '.' all_sequences{seq_idx}.ext];
        all_sequences{seq_idx}.frame_filenames{n} = filename;
    end
    
end
end